export const fontDetectionCandidates = [
  "Inter",
  "Roboto",
  "Arial",
  "Helvetica",
  "Segoe UI",
  "Calibri",
  "Times New Roman",
  "Georgia",
  "Garamond",
  "Palatino",
  "Montserrat",
  "Lato",
  "Open Sans",
  "Poppins",
  "Work Sans",
  "Merriweather",
  "Raleway",
  "Fira Sans",
  "Ubuntu",
  "Noto Sans",
  "Noto Serif",
  "Source Sans Pro",
  "Source Serif Pro",
  "Source Code Pro",
  "Fira Code",
  "Inconsolata",
  "JetBrains Mono",
  "Consolas",
  "Menlo",
  "Monaco",
  "Ubuntu Mono",
  "Tahoma",
  "Trebuchet MS",
  "Verdana",
  "Century Gothic",
  "Book Antiqua",
  "Palatino Linotype",
  "Cambria",
  "Candara",
  "Corbel",
  "Constantia",
  "Franklin Gothic Medium",
  "Arial Black",
  "Arial Narrow",
  "Brush Script MT",
  "Comic Sans MS",
  "Gabriola",
  "Ebrima",
  "Segoe Print",
  "Segoe Script",
  "Bahnschrift",
  "Courier New",
  "Cascadia Code",
  "Avenir",
  "Avenir Next",
  "Geneva",
  "Optima",
  "Lucida Grande",
  "Lucida Sans Unicode",
  "Gill Sans",
  "Futura",
  "American Typewriter",
  "Baskerville",
  "Big Caslon",
  "Bodoni 72",
  "Didot",
  "Copperplate",
  "Hoefler Text",
  "Chalkboard SE",
  "Marker Felt",
  "SFMono-Regular",
  "PingFang SC",
  "Hiragino Sans",
  "Skia",
  "Arial Italic",
  "Arial Bold",
  "Arial Bold Italic",
  "Calibri Light",
  "Calibri Light Italic",
  "Calibri Italic",
  "Calibri Bold",
  "Calibri Bold Italic",
  "Cambria Italic",
  "Cambria Bold",
  "Cambria Bold Italic",
  "Cambria Math",
  "Candara Light",
  "Candara Light Italic",
  "Candara Italic",
  "Candara Bold",
  "Candara Bold Italic",
  "Comic Sans MS Italic",
  "Comic Sans MS Bold",
  "Comic Sans MS Bold Italic",
  "Consolas Italic",
  "Consolas Bold",
  "Consolas Bold Italic",
  "Constantia Italic",
  "Constantia Bold",
  "Constantia Bold Italic",
  "Corbel Light",
  "Corbel Light Italic",
  "Corbel Italic",
  "Corbel Bold",
  "Corbel Bold Italic",
  "Courier New Italic",
  "Courier New Bold",
  "Courier New Bold Italic",
  "Ebrima Bold",
  "Franklin Gothic Medium Italic",
  "Gadugi",
  "Gadugi Bold",
  "Georgia Italic",
  "Georgia Bold",
  "Georgia Bold Italic",
  "HoloLens MDL2 Assets",
  "Impact",
  "Ink Free",
  "Javanese Text",
  "Leelawadee UI",
  "Leelawadee UI Semilight",
  "Leelawadee UI Bold",
  "Lucida Console",
  "Malgun Gothic",
  "Malgun Gothic Bold",
  "Malgun Gothic Semilight",
  "Marlett",
  "Microsoft Himalaya",
  "Microsoft JhengHei Light",
  "Microsoft JhengHei",
  "Microsoft JhengHei Bold",
  "Microsoft JhengHei UI Light",
  "Microsoft JhengHei UI",
  "Microsoft JhengHei UI Bold",
  "Microsoft New Tai Lue",
  "Microsoft New Tai Lue Bold",
  "Microsoft PhagsPa",
  "Microsoft PhagsPa Bold",
  "Microsoft Sans Serif",
  "Microsoft Tai Le",
  "Microsoft Tai Le Bold",
  "Microsoft YaHei Light",
  "Microsoft YaHei",
  "Microsoft YaHei Bold",
  "Microsoft YaHei UI Light",
  "Microsoft YaHei UI",
  "Microsoft YaHei UI Bold",
  "Microsoft Yi Baiti",
  "MingLiU-ExtB",
  "PMingLiU-ExtB",
  "MingLiU_HKSCS-ExtB",
  "Mongolian Baiti",
  "MS Gothic",
  "MS PGothic",
  "MS UI Gothic",
  "MV Boli",
  "Myanmar Text",
  "Myanmar Text Bold",
  "Nirmala UI Semilight",
  "Nirmala UI",
  "Nirmala UI Bold",
  "Palatino Linotype Italic",
  "Palatino Linotype Bold",
  "Palatino Linotype Bold Italic",
  "Segoe MDL2 Assets",
  "Segoe Print Bold",
  "Segoe Script Bold",
  "Segoe UI Light",
  "Segoe UI Light Italic",
  "Segoe UI Semilight",
  "Segoe UI Semilight Italic",
  "Segoe UI Italic",
  "Segoe UI Semibold",
  "Segoe UI Semibold Italic",
  "Segoe UI Bold",
  "Segoe UI Bold Italic",
  "Segoe UI Black",
  "Segoe UI Black Italic",
  "Segoe UI Historic",
  "Segoe UI Emoji",
  "Segoe UI Symbol",
  "SimSun",
  "NSimSun",
  "SimSun-ExtB",
  "Sitka Small",
  "Sitka Small Italic",
  "Sitka Small Bold",
  "Sitka Small Bold Italic",
  "Sitka Text",
  "Sitka Text Italic",
  "Sitka Text Bold",
  "Sitka Text Bold Italic",
  "Sitka Subheading",
  "Sitka Subheading Italic",
  "Sitka Subheading Bold",
  "Sitka Subheading Bold Italic",
  "Sitka Heading",
  "Sitka Heading Italic",
  "Sitka Heading Bold",
  "Sitka Heading Bold Italic",
  "Sitka Display",
  "Sitka Display Italic",
  "Sitka Display Bold",
  "Sitka Display Bold Italic",
  "Sitka Banner",
  "Sitka Banner Italic",
  "Sitka Banner Bold",
  "Sitka Banner Bold Italic",
  "Sylfaen",
  "Symbol",
  "Tahoma Bold",
  "Times New Roman Italic",
  "Times New Roman Bold",
  "Times New Roman Bold Italic",
  "Trebuchet MS Italic",
  "Trebuchet MS Bold",
  "Trebuchet MS Bold Italic",
  "Verdana Italic",
  "Verdana Bold",
  "Verdana Bold Italic",
  "Webdings",
  "Wingdings",
  "Yu Gothic Light",
  "Yu Gothic Regular",
  "Yu Gothic Medium",
  "Yu Gothic Bold",
  "Yu Gothic UI Light",
  "Yu Gothic UI Semilight",
  "Yu Gothic UI Regular",
  "Yu Gothic UI Semibold",
  "Yu Gothic UI Bold",
  "Bitstream Charter",
  "C059",
  "Cantarell",
  "Cantarell Extra Bold",
  "Cantarell Light",
  "Cantarell Thin",
  "Courier 10 Pitch",
  "D050000L",
  "DejaVu Sans",
  "DejaVu Sans Mono",
  "DejaVu Serif",
  "DM Mono",
  "DM Mono Light",
  "DM Mono Medium",
  "Droid Sans Fallback",
  "FreeMono",
  "FreeSans",
  "FreeSerif",
  "Hack",
  "IBM Plex Mono",
  "IBM Plex Mono ExtLt",
  "IBM Plex Mono Light",
  "IBM Plex Mono Medm",
  "IBM Plex Mono SmBld",
  "IBM Plex Mono Text",
  "IBM Plex Mono Thin",
  "IBM Plex Sans",
  "IBM Plex Sans Arabic",
  "IBM Plex Sans Arabic ExtLt",
  "IBM Plex Sans Arabic Light",
  "IBM Plex Sans Arabic Medm",
  "IBM Plex Sans Arabic SmBld",
  "IBM Plex Sans Arabic Text",
  "IBM Plex Sans Arabic Thin",
  "IBM Plex Sans Condensed",
  "IBM Plex Sans Cond",
  "IBM Plex Sans Cond ExtLt",
  "IBM Plex Sans Cond Light",
  "IBM Plex Sans Cond Medm",
  "IBM Plex Sans Cond SmBld",
  "IBM Plex Sans Cond Text",
  "IBM Plex Sans Cond Thin",
  "IBM Plex Sans Devanagari",
  "IBM Plex Sans Devanagari ExtLt",
  "IBM Plex Sans Devanagari Light",
  "IBM Plex Sans Devanagari Medm",
  "IBM Plex Sans Devanagari SmBld",
  "IBM Plex Sans Devanagari Text",
  "IBM Plex Sans Devanagari Thin",
  "IBM Plex Sans Hebrew",
  "IBM Plex Sans Hebrew ExtLt",
  "IBM Plex Sans Hebrew Light",
  "IBM Plex Sans Hebrew Medm",
  "IBM Plex Sans Hebrew SmBld",
  "IBM Plex Sans Hebrew Text",
  "IBM Plex Sans Hebrew Thin",
  "IBM Plex Sans ExtLt",
  "IBM Plex Sans Light",
  "IBM Plex Sans Medm",
  "IBM Plex Sans SmBld",
  "IBM Plex Sans Text",
  "IBM Plex Sans Thin",
  "IBM Plex Sans Thai",
  "IBM Plex Sans Thai ExtLt",
  "IBM Plex Sans Thai Light",
  "IBM Plex Sans Thai Medm",
  "IBM Plex Sans Thai SmBld",
  "IBM Plex Sans Thai Text",
  "IBM Plex Sans Thai Thin",
  "IBM Plex Sans Thai Looped",
  "IBM Plex Sans Thai Looped ExtLt",
  "IBM Plex Sans Thai Looped Light",
  "IBM Plex Sans Thai Looped Medm",
  "IBM Plex Sans Thai Looped SmBld",
  "IBM Plex Sans Thai Looped Text",
  "IBM Plex Sans Thai Looped Thin",
  "IBM Plex Sans Var",
  "IBM Plex Serif",
  "IBM Plex Serif ExtLt",
  "IBM Plex Serif Light",
  "IBM Plex Serif Medm",
  "IBM Plex Serif SmBld",
  "IBM Plex Serif Text",
  "IBM Plex Serif Thin",
  "IPAGothic",
  "IPAゴシック",
  "IPAPGothic",
  "IPA Pゴシック",
  "䥐䅐䝯瑨楣",
  "Liberation Mono",
  "Liberation Sans",
  "Liberation Sans Narrow",
  "Liberation Serif",
  "Loma",
  "Nimbus Mono PS",
  "Nimbus Roman",
  "Nimbus Sans",
  "Nimbus Sans Narrow",
  "Noto Color Emoji",
  "Noto Kufi Arabic",
  "Noto Looped Lao",
  "Noto Looped Lao Bold",
  "Noto Looped Lao Regular",
  "Noto Looped Lao UI",
  "Noto Looped Lao UI Bold",
  "Noto Looped Lao UI Regular",
  "Noto Looped Thai",
  "Noto Looped Thai Bold",
  "Noto Looped Thai Regular",
  "Noto Looped Thai UI",
  "Noto Looped Thai UI Bold",
  "Noto Looped Thai UI Regular",
  "Noto Mono",
  "Noto Music",
  "Noto Naskh Arabic",
  "Noto Naskh Arabic UI",
  "Noto Nastaliq Urdu",
  "Noto Rashi Hebrew",
  "Noto Sans Adlam",
  "Noto Sans Adlam Unjoined",
  "Noto Sans Anatolian Hieroglyphs",
  "Noto Sans AnatoHiero",
  "Noto Sans Arabic",
  "Noto Sans Arabic UI",
  "Noto Sans Armenian",
  "Noto Sans Avestan",
  "Noto Sans Balinese",
  "Noto Sans Bamum",
  "Noto Sans Bassa Vah",
  "Noto Sans Batak",
  "Noto Sans Bengali",
  "Noto Sans Bengali UI",
  "Noto Sans Bhaiksuki",
  "Noto Sans Brahmi",
  "Noto Sans Buginese",
  "Noto Sans Buhid",
  "Noto Sans Canadian Aboriginal",
  "Noto Sans CanAborig",
  "Noto Sans Carian",
  "Noto Sans Caucasian Albanian",
  "Noto Sans CaucAlban",
  "Noto Sans Chakma",
  "Noto Sans Cham",
  "Noto Sans Cherokee",
  "Noto Sans CJK HK",
  "Noto Sans CJK JP",
  "Noto Sans CJK KR",
  "Noto Sans CJK SC",
  "Noto Sans CJK TC",
  "Noto Sans Coptic",
  "Noto Sans Cuneiform",
  "Noto Sans Cypriot",
  "Noto Sans Deseret",
  "Noto Sans Devanagari",
  "Noto Sans Devanagari UI",
  "Noto Sans Display",
  "Noto Sans Duployan",
  "Noto Sans Egyptian Hieroglyphs",
  "Noto Sans EgyptHiero",
  "Noto Sans Elbasan",
  "Noto Sans Elymaic",
  "Noto Sans Ethiopic",
  "Noto Sans Georgian",
  "Noto Sans Glagolitic",
  "Noto Sans Gothic",
  "Noto Sans Grantha",
  "Noto Sans Gujarati",
  "Noto Sans Gujarati UI",
  "Noto Sans Gunjala Gondi",
  "Noto Sans Gurmukhi",
  "Noto Sans Gurmukhi UI",
  "Noto Sans Hanifi Rohingya",
  "Noto Sans Hanunoo",
  "Noto Sans Hatran",
  "Noto Sans Hebrew",
  "Noto Sans Imperial Aramaic",
  "Noto Sans ImpAramaic",
  "Noto Sans Indic Siyaq Numbers",
  "Noto Sans Inscriptional Pahlavi",
  "Noto Sans InsPahlavi",
  "Noto Sans Inscriptional Parthian",
  "Noto Sans InsParthi",
  "Noto Sans Javanese",
  "Noto Sans Kaithi",
  "Noto Sans Kannada",
  "Noto Sans Kannada UI",
  "Noto Sans Kayah Li",
  "Noto Sans Kharoshthi",
  "Noto Sans Khmer",
  "Noto Sans Khmer UI",
  "Noto Sans Khojki",
  "Noto Sans Khudawadi",
  "Noto Sans Lao",
  "Noto Sans Lao UI",
  "Noto Sans Lepcha",
  "Noto Sans Limbu",
  "Noto Sans Linear A",
  "Noto Sans Linear B",
  "Noto Sans Lisu",
  "Noto Sans Lycian",
  "Noto Sans Lydian",
  "Noto Sans Mahajani",
  "Noto Sans Malayalam",
  "Noto Sans Malayalam UI",
  "Noto Sans Mandaic",
  "Noto Sans Manichaean",
  "Noto Sans Marchen",
  "Noto Sans Masaram Gondi",
  "Noto Sans Math",
  "Noto Sans Mayan Numerals",
  "Noto Sans Medefaidrin",
  "Noto Sans Meetei Mayek",
  "Noto Sans Mende Kikakui",
  "Noto Sans Meroitic",
  "Noto Sans Miao",
  "Noto Sans Modi",
  "Noto Sans Mongolian",
  "Noto Sans Mono",
  "Noto Sans Mono CJK HK",
  "Noto Sans Mono CJK JP",
  "Noto Sans Mono CJK KR",
  "Noto Sans Mono CJK SC",
  "Noto Sans Mono CJK TC",
  "Noto Sans Mro",
  "Noto Sans Multani",
  "Noto Sans Myanmar",
  "Noto Sans Myanmar UI",
  "Noto Sans Nabataean",
  "Noto Sans Newa",
  "Noto Sans New Tai Lue",
  "Noto Sans NKo",
  "Noto Sans Nushu",
  "Noto Sans Ogham",
  "Noto Sans Ol Chiki",
  "Noto Sans Old Hungarian",
  "Noto Sans OldHung",
  "Noto Sans Old Italic",
  "Noto Sans Old North Arabian",
  "Noto Sans OldNorArab",
  "Noto Sans Old Permic",
  "Noto Sans Old Persian",
  "Noto Sans Old Sogdian",
  "Noto Sans Old South Arabian",
  "Noto Sans OldSouArab",
  "Noto Sans Old Turkic",
  "Noto Sans Oriya",
  "Noto Sans Oriya UI",
  "Noto Sans Osage",
  "Noto Sans Osmanya",
  "Noto Sans Pahawh Hmong",
  "Noto Sans Palmyrene",
  "Noto Sans Pau Cin Hau",
  "Noto Sans PhagsPa",
  "Noto Sans Phoenician",
  "Noto Sans Psalter Pahlavi",
  "Noto Sans PsaPahlavi",
  "Noto Sans Rejang",
  "Noto Sans Runic",
  "Noto Sans Samaritan",
  "Noto Sans Saurashtra",
  "Noto Sans Sharada",
  "Noto Sans Shavian",
  "Noto Sans Siddham",
  "Noto Sans SignWriting",
  "Noto Sans SignWrit",
  "Noto Sans Sinhala",
  "Noto Sans Sinhala UI",
  "Noto Sans Sogdian",
  "Noto Sans Sora Sompeng",
  "Noto Sans Soyombo",
  "Noto Sans Sundanese",
  "Noto Sans Syloti Nagri",
  "Noto Sans Symbols",
  "Noto Sans Syriac",
  "Noto Sans Tagalog",
  "Noto Sans Tagbanwa",
  "Noto Sans Tai Le",
  "Noto Sans Tai Tham",
  "Noto Sans Tai Viet",
  "Noto Sans Takri",
  "Noto Sans Tamil",
  "Noto Sans Tamil Supplement",
  "Noto Sans Tamil UI",
  "Noto Sans Telugu",
  "Noto Sans Telugu UI",
  "Noto Sans Thaana",
  "Noto Sans Thai",
  "Noto Sans Thai UI",
  "Noto Sans Tifinagh",
  "Noto Sans Tifinagh Adrar",
  "Noto Sans Tifinagh Agraw Imazighen",
  "Noto Sans Tifinagh Ahaggar",
  "Noto Sans Tifinagh Air",
  "Noto Sans Tifinagh APT",
  "Noto Sans Tifinagh Azawagh",
  "Noto Sans Tifinagh Ghat",
  "Noto Sans Tifinagh Hawad",
  "Noto Sans Tifinagh Rhissa Ixa",
  "Noto Sans Tifinagh SIL",
  "Noto Sans Tifinagh Tawellemmet",
  "Noto Sans Tirhuta",
  "Noto Sans Ugaritic",
  "Noto Sans Vai",
  "Noto Sans Wancho",
  "Noto Sans Warang Citi",
  "Noto Sans Yi",
  "Noto Sans Zanabazar Square",
  "Noto Sans Zanabazar",
  "Noto Serif Ahom",
  "Noto Serif Armenian",
  "Noto Serif Balinese",
  "Noto Serif Bengali",
  "Noto Serif CJK HK",
  "Noto Serif CJK JP",
  "Noto Serif CJK KR",
  "Noto Serif CJK SC",
  "Noto Serif CJK TC",
  "Noto Serif Devanagari",
  "Noto Serif Display",
  "Noto Serif Dogra",
  "Noto Serif Ethiopic",
  "Noto Serif Georgian",
  "Noto Serif Grantha",
  "Noto Serif Gujarati",
  "Noto Serif Gurmukhi",
  "Noto Serif Hebrew",
  "Noto Serif Hmong Nyiakeng",
  "Noto Serif Kannada",
  "Noto Serif Khmer",
  "Noto Serif Khojki",
  "Noto Serif Lao",
  "Noto Serif Malayalam",
  "Noto Serif Myanmar",
  "Noto Serif Sinhala",
  "Noto Serif Tamil",
  "Noto Serif Tamil Slanted",
  "Noto Serif Tangut",
  "Noto Serif Telugu",
  "Noto Serif Thai",
  "Noto Serif Tibetan",
  "Noto Serif Yezidi",
  "Noto Traditional Nushu",
  "OpenSymbol",
  "P052",
  "Space Grotesk",
  "Space Grotesk Light",
  "Space Grotesk Medium",
  "Standard Symbols PS",
  "Symbola",
  "Noto Sans Symbols2",
  "Ubuntu Sans",
  "Ubuntu Sans Mono",
  "Unifont",
  "Unifont CSUR",
  "Unifont-JP",
  "Unifont Sample",
  "Unifont Upper",
  "URW Bookman",
  "URW Gothic",
  "WenQuanYi Zen Hei Mono",
  "文泉驛等寬正黑",
  "文泉驿等宽正黑",
  "WenQuanYi Zen Hei Sharp",
  "文泉驛點陣正黑",
  "文泉驿点阵正黑",
  "WenQuanYi Zen Hei",
  "文泉驛正黑",
  "文泉驿正黑",
  "Z003",
  "Cascadia Code ExtraLight *",
  "Cascadia Code ExtraLight Italic *",
  "Cascadia Code Light *",
  "Cascadia Code Light Italic *",
  "Cascadia Code SemiLight *",
  "Cascadia Code SemiLight Italic *",
  "Cascadia Code Regular *",
  "Cascadia Code Italic *",
  "Cascadia Code SemiBold *",
  "Cascadia Code SemiBold Italic *",
  "Cascadia Code Bold *",
  "Cascadia Code Bold Italic *",
  "Cascadia Mono ExtraLight *",
  "Cascadia Mono ExtraLight Italic *",
  "Cascadia Mono Light *",
  "Cascadia Mono Light Italic *",
  "Cascadia Mono SemiLight *",
  "Cascadia Mono SemiLight Italic *",
  "Cascadia Mono Regular *",
  "Cascadia Mono Italic *",
  "Cascadia Mono SemiBold *",
  "Cascadia Mono SemiBold Italic *",
  "Cascadia Mono Bold *",
  "Cascadia Mono Bold Italic *",
  "Segoe Fluent Icons *",
  "Segoe UI Variable Display Light *",
  "Segoe UI Variable Display Semilight *",
  "Segoe UI Variable Display Regular *",
  "Segoe UI Variable Display Semibold *",
  "Segoe UI Variable Display Bold *",
  "Segoe UI Variable Small Light *",
  "Segoe UI Variable Small Semilight *",
  "Segoe UI Variable Small Regular *",
  "Segoe UI Variable Small Semibold *",
  "Segoe UI Variable Small Bold *",
  "Segoe UI Variable Text Light *",
  "Segoe UI Variable Text Semilight *",
  "Segoe UI Variable Text Regular *",
  "Segoe UI Variable Text Semibold *",
  "Segoe UI Variable Text Bold *",
  "Sitka Banner Semibold *",
  "Sitka Banner Semibold Italic *",
  "Sitka Display Semibold *",
  "Sitka Display Semibold Italic *",
  "Sitka Small Semibold *",
  "Sitka Small Semibold Italic *",
  "Sitka Heading Semibold *",
  "Sitka Heading Semibold Italic *",
  "Sitka Subheading Semibold *",
  "Sitka Subheading Semibold Italic *",
  "Sitka Text Semibold *",
  "Sitka Text Semibold Italic *",
  "Adobe Courier",
  "Adobe Helvetica",
  "Adobe New Century Schoolbook",
  "Adobe Times",
  "Adobe Utopia",
  "Adwaita Mono",
  "Adwaita Sans",
  "Arabic Newspaper",
  "B&H Lucida",
  "B&H LucidaBright",
  "B&H LucidaTypewriter",
  "Bitstream Terminal",
  "cursor.pcf",
  "deccurs.pcf",
  "decsess.pcf",
  "DEC Terminal",
  "DejaVu Math TeX Gyre",
  "DejaVu Sans,DejaVu Sans Condensed",
  "DejaVu Sans,DejaVu Sans Light",
  "DejaVu Serif,DejaVu Serif Condensed",
  "East Syriac Adiabene",
  "East Syriac Ctesiphon",
  "Estrangelo Antioch",
  "Estrangelo Edessa",
  "Estrangelo Midyat",
  "Estrangelo Nisibin",
  "Estrangelo Nisibin Outline",
  "Estrangelo Quenneshrin",
  "Estrangelo Talada",
  "Estrangelo TurAbdin",
  "Goha-Tibeb Zemen",
  "Hack Nerd Font",
  "Hack Nerd Font Mono",
  "Hack Nerd Font Propo",
  "Iosevka",
  "Iosevka,Iosevka Extended",
  "Iosevka,Iosevka Extended Oblique",
  "Iosevka,Iosevka Extrabold",
  "Iosevka,Iosevka Extrabold Extended",
  "Iosevka,Iosevka Extrabold Oblique",
  "Iosevka,Iosevka Extralight",
  "Iosevka,Iosevka Extralight Extended",
  "Iosevka,Iosevka Extralight Oblique",
  "Iosevka,Iosevka Heavy",
  "Iosevka,Iosevka Heavy Extended",
  "Iosevka,Iosevka Heavy Extended Oblique",
  "Iosevka,Iosevka Heavy Oblique",
  "Iosevka,Iosevka Light",
  "Iosevka,Iosevka Light Extended",
  "Iosevka,Iosevka Light Extended Oblique",
  "Iosevka,Iosevka Light Oblique",
  "Iosevka,Iosevka Md Ex Obl",
  "Iosevka,Iosevka Medium",
  "Iosevka,Iosevka Medium Extended",
  "Iosevka,Iosevka Medium Oblique",
  "Iosevka,Iosevka Oblique",
  "Iosevka,Iosevka Semibold",
  "Iosevka,Iosevka Semibold Extended",
  "Iosevka,Iosevka Semibold Oblique",
  "Iosevka,Iosevka SmBd Ex Obl",
  "Iosevka,Iosevka Thin",
  "Iosevka,Iosevka Thin Extended",
  "Iosevka,Iosevka Thin Extended Oblique",
  "Iosevka,Iosevka Thin Oblique",
  "Iosevka,Iosevka XBd Ex Obl",
  "Iosevka,Iosevka XLt Ex Obl",
  "Iosevka Nerd Font,Iosevka NF",
  "Iosevka Nerd Font,Iosevka NF,Iosevka NF ExtraBold",
  "Iosevka Nerd Font,Iosevka NF,Iosevka NF ExtraBold Obl",
  "Iosevka Nerd Font,Iosevka NF,Iosevka NF ExtraLight",
  "Iosevka Nerd Font,Iosevka NF,Iosevka NF ExtraLight Obl",
  "Iosevka Nerd Font,Iosevka NF,Iosevka NF Heavy",
  "Iosevka Nerd Font,Iosevka NF,Iosevka NF Heavy Obl",
  "Iosevka Nerd Font,Iosevka NF,Iosevka NF Light",
  "Iosevka Nerd Font,Iosevka NF,Iosevka NF Light Obl",
  "Iosevka Nerd Font,Iosevka NF,Iosevka NF Medium",
  "Iosevka Nerd Font,Iosevka NF,Iosevka NF Medium Obl",
  "Iosevka Nerd Font,Iosevka NF,Iosevka NF Obl",
  "Iosevka Nerd Font,Iosevka NF,Iosevka NF SemiBold",
  "Iosevka Nerd Font,Iosevka NF,Iosevka NF SemiBold Obl",
  "Iosevka Nerd Font,Iosevka NF,Iosevka NF Thin",
  "Iosevka Nerd Font,Iosevka NF,Iosevka NF Thin Obl",
  "Iosevka Nerd Font Mono,Iosevka NFM",
  "Iosevka Nerd Font Mono,Iosevka NFM,Iosevka NFM ExtraBold",
  "Iosevka Nerd Font Mono,Iosevka NFM,Iosevka NFM ExtraBold Obl",
  "Iosevka Nerd Font Mono,Iosevka NFM,Iosevka NFM ExtraLight",
  "Iosevka Nerd Font Mono,Iosevka NFM,Iosevka NFM ExtraLight Obl",
  "Iosevka Nerd Font Mono,Iosevka NFM,Iosevka NFM Heavy",
  "Iosevka Nerd Font Mono,Iosevka NFM,Iosevka NFM Heavy Obl",
  "Iosevka Nerd Font Mono,Iosevka NFM,Iosevka NFM Light",
  "Iosevka Nerd Font Mono,Iosevka NFM,Iosevka NFM Light Obl",
  "Iosevka Nerd Font Mono,Iosevka NFM,Iosevka NFM Medium",
  "Iosevka Nerd Font Mono,Iosevka NFM,Iosevka NFM Medium Obl",
  "Iosevka Nerd Font Mono,Iosevka NFM,Iosevka NFM Obl",
  "Iosevka Nerd Font Mono,Iosevka NFM,Iosevka NFM SemiBold",
  "Iosevka Nerd Font Mono,Iosevka NFM,Iosevka NFM SemiBold Obl",
  "Iosevka Nerd Font Mono,Iosevka NFM,Iosevka NFM Thin",
  "Iosevka Nerd Font Mono,Iosevka NFM,Iosevka NFM Thin Obl",
  "Iosevka Nerd Font Propo,Iosevka NFP",
  "Iosevka Nerd Font Propo,Iosevka NFP,Iosevka NFP ExtraBold",
  "Iosevka Nerd Font Propo,Iosevka NFP,Iosevka NFP ExtraBold Obl",
  "Iosevka Nerd Font Propo,Iosevka NFP,Iosevka NFP ExtraLight",
  "Iosevka Nerd Font Propo,Iosevka NFP,Iosevka NFP ExtraLight Obl",
  "Iosevka Nerd Font Propo,Iosevka NFP,Iosevka NFP Heavy",
  "Iosevka Nerd Font Propo,Iosevka NFP,Iosevka NFP Heavy Obl",
  "Iosevka Nerd Font Propo,Iosevka NFP,Iosevka NFP Light",
  "Iosevka Nerd Font Propo,Iosevka NFP,Iosevka NFP Light Obl",
  "Iosevka Nerd Font Propo,Iosevka NFP,Iosevka NFP Medium",
  "Iosevka Nerd Font Propo,Iosevka NFP,Iosevka NFP Medium Obl",
  "Iosevka Nerd Font Propo,Iosevka NFP,Iosevka NFP Obl",
  "Iosevka Nerd Font Propo,Iosevka NFP,Iosevka NFP SemiBold",
  "Iosevka Nerd Font Propo,Iosevka NFP,Iosevka NFP SemiBold Obl",
  "Iosevka Nerd Font Propo,Iosevka NFP,Iosevka NFP Thin",
  "Iosevka Nerd Font Propo,Iosevka NFP,Iosevka NFP Thin Obl",
  "LDFComicSans",
  "LDFComicSansBold",
  "LDFComicSansHairline",
  "LDFComicSansLight",
  "micro.pcf",
  "Misc Fixed",
  "Misc Fixed Wide",
  "mtx",
  "MUTT ClearlyU Alternate Glyphs Wide",
  "MUTT ClearlyU PUA",
  "MUTT ClearlyU Wide",
  "Noto Fangsong KSS Rotated",
  "Noto Fangsong KSS Vertical",
  "Noto Kufi Arabic,Noto Kufi Arabic Black",
  "Noto Kufi Arabic,Noto Kufi Arabic Light",
  "Noto Kufi Arabic,Noto Kufi Arabic Medium",
  "Noto Kufi Arabic,Noto Kufi Arabic Thin",
  "Noto Naskh Arabic,Noto Naskh Arabic Medium",
  "Noto Naskh Arabic UI,Noto Naskh Arabic UI Medium",
  "Noto Rashi Hebrew,Noto Rashi Hebrew Blk",
  "Noto Rashi Hebrew,Noto Rashi Hebrew Light",
  "Noto Rashi Hebrew,Noto Rashi Hebrew Med",
  "Noto Rashi Hebrew,Noto Rashi Hebrew Thin",
  "Noto Sans Arabic,Noto Sans Arabic Blk",
  "Noto Sans Arabic,Noto Sans Arabic Light",
  "Noto Sans Arabic,Noto Sans Arabic Med",
  "Noto Sans Arabic,Noto Sans Arabic Thin",
  "Noto Sans Arabic UI,Noto Sans Arabic UI Bk",
  "Noto Sans Arabic UI,Noto Sans Arabic UI Lt",
  "Noto Sans Arabic UI,Noto Sans Arabic UI Md",
  "Noto Sans Arabic UI,Noto Sans Arabic UI Th",
  "Noto Sans Armenian,Noto Sans Armenian Black",
  "Noto Sans Armenian,Noto Sans Armenian Light",
  "Noto Sans Armenian,Noto Sans Armenian Medium",
  "Noto Sans Armenian,Noto Sans Armenian Thin",
  "Noto Sans Balinese,Noto Sans Balinese Medium",
  "Noto Sans Bamum,Noto Sans Bamum Medium",
  "Noto Sans Bassa Vah,Noto Sans Bassa Vah Medium",
  "Noto Sans Bengali,Noto Sans Bengali Black",
  "Noto Sans Bengali,Noto Sans Bengali Light",
  "Noto Sans Bengali,Noto Sans Bengali Medium",
  "Noto Sans Bengali,Noto Sans Bengali Thin",
  "Noto Sans Bengali UI,Noto Sans Bengali UI Black",
  "Noto Sans Bengali UI,Noto Sans Bengali UI Light",
  "Noto Sans Bengali UI,Noto Sans Bengali UI Medium",
  "Noto Sans Bengali UI,Noto Sans Bengali UI Thin",
  "Noto Sans Canadian Aboriginal,Noto Sans Canadian Aboriginal Black",
  "Noto Sans Canadian Aboriginal,Noto Sans Canadian Aboriginal Light",
  "Noto Sans Canadian Aboriginal,Noto Sans Canadian Aboriginal Medium",
  "Noto Sans Canadian Aboriginal,Noto Sans Canadian Aboriginal Thin",
  "Noto Sans Cham,Noto Sans Cham Black",
  "Noto Sans Cham,Noto Sans Cham Light",
  "Noto Sans Cham,Noto Sans Cham Medium",
  "Noto Sans Cham,Noto Sans Cham Thin",
  "Noto Sans Cherokee,Noto Sans Cherokee Black",
  "Noto Sans Cherokee,Noto Sans Cherokee Light",
  "Noto Sans Cherokee,Noto Sans Cherokee Medium",
  "Noto Sans Cherokee,Noto Sans Cherokee Thin",
  "Noto Sans Chorasmian",
  "Noto Sans Cypro Minoan",
  "Noto Sans Devanagari,Noto Sans Devanagari Black",
  "Noto Sans Devanagari,Noto Sans Devanagari Light",
  "Noto Sans Devanagari,Noto Sans Devanagari Medium",
  "Noto Sans Devanagari,Noto Sans Devanagari Thin",
  "Noto Sans Devanagari UI,Noto Sans Devanagari UI Black",
  "Noto Sans Devanagari UI,Noto Sans Devanagari UI Light",
  "Noto Sans Devanagari UI,Noto Sans Devanagari UI Medium",
  "Noto Sans Devanagari UI,Noto Sans Devanagari UI Thin",
  "Noto Sans Egyptian Hieroglyphs,Noto Sans EgyptHiero",
  "Noto Sans Ethiopic,Noto Sans Ethiopic Black",
  "Noto Sans Ethiopic,Noto Sans Ethiopic Light",
  "Noto Sans Ethiopic,Noto Sans Ethiopic Medium",
  "Noto Sans Ethiopic,Noto Sans Ethiopic Thin",
  "Noto Sans Georgian,Noto Sans Georgian Black",
  "Noto Sans Georgian,Noto Sans Georgian Bold",
  "Noto Sans Georgian,Noto Sans Georgian Light",
  "Noto Sans Georgian,Noto Sans Georgian Medium",
  "Noto Sans Georgian,Noto Sans Georgian Thin",
  "Noto Sans Gujarati,Noto Sans Gujarati Black",
  "Noto Sans Gujarati,Noto Sans Gujarati Light",
  "Noto Sans Gujarati,Noto Sans Gujarati Medium",
  "Noto Sans Gujarati,Noto Sans Gujarati Thin",
  "Noto Sans Gujarati UI,Noto Sans Gujarati UI Black",
  "Noto Sans Gujarati UI,Noto Sans Gujarati UI Light",
  "Noto Sans Gujarati UI,Noto Sans Gujarati UI Medium",
  "Noto Sans Gujarati UI,Noto Sans Gujarati UI Thin",
  "Noto Sans Gunjala Gondi,Noto Sans Gunjala Gondi Medium",
  "Noto Sans Gurmukhi,Noto Sans Gurmukhi Black",
  "Noto Sans Gurmukhi,Noto Sans Gurmukhi Light",
  "Noto Sans Gurmukhi,Noto Sans Gurmukhi Medium",
  "Noto Sans Gurmukhi,Noto Sans Gurmukhi Thin",
  "Noto Sans Gurmukhi UI,Noto Sans Gurmukhi UI Black",
  "Noto Sans Gurmukhi UI,Noto Sans Gurmukhi UI Light",
  "Noto Sans Gurmukhi UI,Noto Sans Gurmukhi UI Medium",
  "Noto Sans Gurmukhi UI,Noto Sans Gurmukhi UI Thin",
  "Noto Sans Hanifi Rohingya,Noto Sans Hanifi Rohingya Medium",
  "Noto Sans Hebrew,Noto Sans Hebrew Black",
  "Noto Sans Hebrew,Noto Sans Hebrew Light",
  "Noto Sans Hebrew,Noto Sans Hebrew Medium",
  "Noto Sans Hebrew,Noto Sans Hebrew Thin",
  "Noto Sans Imperial Aramaic,Noto Sans ImpAramaic",
  "Noto Sans Inscriptional Pahlavi,Noto Sans InsPahlavi",
  "Noto Sans Kannada,Noto Sans Kannada Black",
  "Noto Sans Kannada,Noto Sans Kannada Light",
  "Noto Sans Kannada,Noto Sans Kannada Medium",
  "Noto Sans Kannada,Noto Sans Kannada Thin",
  "Noto Sans Kannada UI,Noto Sans Kannada UI Black",
  "Noto Sans Kannada UI,Noto Sans Kannada UI Light",
  "Noto Sans Kannada UI,Noto Sans Kannada UI Medium",
  "Noto Sans Kannada UI,Noto Sans Kannada UI Thin",
  "Noto Sans Kawi",
  "Noto Sans Kayah Li,Noto Sans Kayah Li Medium",
  "Noto Sans Khmer,Noto Sans Khmer Black",
  "Noto Sans Khmer,Noto Sans Khmer Light",
  "Noto Sans Khmer,Noto Sans Khmer Medium",
  "Noto Sans Khmer,Noto Sans Khmer Thin",
  "Noto Sans Lao Looped",
  "Noto Sans Lao Looped,Noto Sans Lao Looped Black",
  "Noto Sans Lao Looped,Noto Sans Lao Looped Light",
  "Noto Sans Lao Looped,Noto Sans Lao Looped Medium",
  "Noto Sans Lao Looped,Noto Sans Lao Looped Thin",
  "Noto Sans Lao,Noto Sans Lao Black",
  "Noto Sans Lao,Noto Sans Lao Light",
  "Noto Sans Lao,Noto Sans Lao Medium",
  "Noto Sans Lao,Noto Sans Lao Thin",
  "Noto Sans Lisu,Noto Sans Lisu Medium",
  "Noto Sans Malayalam,Noto Sans Malayalam Black",
  "Noto Sans Malayalam,Noto Sans Malayalam Light",
  "Noto Sans Malayalam,Noto Sans Malayalam Medium",
  "Noto Sans Malayalam,Noto Sans Malayalam Thin",
  "Noto Sans Malayalam UI,Noto Sans Malayalam UI Black",
  "Noto Sans Malayalam UI,Noto Sans Malayalam UI Light",
  "Noto Sans Malayalam UI,Noto Sans Malayalam UI Medium",
  "Noto Sans Malayalam UI,Noto Sans Malayalam UI Thin",
  "Noto Sans Medefaidrin,Noto Sans Medefaidrin Medium",
  "Noto Sans Meetei Mayek,Noto Sans Meetei Mayek Black",
  "Noto Sans Meetei Mayek,Noto Sans Meetei Mayek Light",
  "Noto Sans Meetei Mayek,Noto Sans Meetei Mayek Medium",
  "Noto Sans Meetei Mayek,Noto Sans Meetei Mayek Thin",
  "Noto Sans Mono,Noto Sans Mono Black",
  "Noto Sans Mono,Noto Sans Mono Light",
  "Noto Sans Mono,Noto Sans Mono Medium",
  "Noto Sans Mono,Noto Sans Mono Thin",
  "Noto Sans Myanmar,Noto Sans Myanmar Black",
  "Noto Sans Myanmar,Noto Sans Myanmar Light",
  "Noto Sans Myanmar,Noto Sans Myanmar Medium",
  "Noto Sans Myanmar,Noto Sans Myanmar Thin",
  "Noto Sans Nag Mundari",
  "Noto Sans Nandinagari",
  "Noto Sans New Tai Lue,Noto Sans New Tai Lue Medium",
  "Noto Sans NKo Unjoined",
  "Noto Sans,Noto Sans Black",
  "Noto Sans,Noto Sans Light",
  "Noto Sans,Noto Sans Medium",
  "Noto Sans,Noto Sans Thin",
  "Noto Sans Ol Chiki,Noto Sans Ol Chiki Medium",
  "Noto Sans Oriya,Noto Sans Oriya Blk",
  "Noto Sans Oriya,Noto Sans Oriya Thin",
  "Noto Sans Psalter Pahlavi,Noto Sans PsaPahlavi",
  "Noto Sans Sinhala,Noto Sans Sinhala Black",
  "Noto Sans Sinhala,Noto Sans Sinhala Black Condensed",
  "Noto Sans Sinhala,Noto Sans Sinhala Light",
  "Noto Sans Sinhala,Noto Sans Sinhala Medium",
  "Noto Sans Sinhala,Noto Sans Sinhala Thin",
  "Noto Sans Sinhala,Noto Sans Sinhala Thin Condensed",
  "Noto Sans Sinhala UI,Noto Sans Sinhala UI Black",
  "Noto Sans Sinhala UI,Noto Sans Sinhala UI Light",
  "Noto Sans Sinhala UI,Noto Sans Sinhala UI Medium",
  "Noto Sans Sinhala UI,Noto Sans Sinhala UI Thin",
  "Noto Sans Sora Sompeng,Noto Sans Sora Sompeng Medium",
  "Noto Sans Sunuwar",
  "Noto Sans Symbols 2",
  "Noto Sans Symbols,Noto Sans Symbols Black",
  "Noto Sans Symbols,Noto Sans Symbols Light",
  "Noto Sans Symbols,Noto Sans Symbols Medium",
  "Noto Sans Symbols,Noto Sans Symbols Thin",
  "Noto Sans Syriac Eastern",
  "Noto Sans Syriac Eastern,Noto Sans Syriac Eastern Black",
  "Noto Sans Syriac Eastern,Noto Sans Syriac Eastern Thin",
  "Noto Sans Syriac,Noto Sans Syriac Black",
  "Noto Sans Syriac,Noto Sans Syriac Thin",
  "Noto Sans Syriac Western",
  "Noto Sans Syriac Western,Noto Sans Syriac Western Black",
  "Noto Sans Syriac Western,Noto Sans Syriac Western Thin",
  "Noto Sans Tai Tham,Noto Sans Tai Tham Medium",
  "Noto Sans Tamil,Noto Sans Tamil Black",
  "Noto Sans Tamil,Noto Sans Tamil Light",
  "Noto Sans Tamil,Noto Sans Tamil Medium",
  "Noto Sans Tamil,Noto Sans Tamil Thin",
  "Noto Sans Tamil UI,Noto Sans Tamil UI Black",
  "Noto Sans Tamil UI,Noto Sans Tamil UI Light",
  "Noto Sans Tamil UI,Noto Sans Tamil UI Medium",
  "Noto Sans Tamil UI,Noto Sans Tamil UI Thin",
  "Noto Sans Tangsa",
  "Noto Sans Tangsa,Noto Sans Tangsa Medium",
  "Noto Sans Telugu,Noto Sans Telugu Black",
  "Noto Sans Telugu,Noto Sans Telugu Light",
  "Noto Sans Telugu,Noto Sans Telugu Medium",
  "Noto Sans Telugu,Noto Sans Telugu Thin",
  "Noto Sans Telugu UI,Noto Sans Telugu UI Black",
  "Noto Sans Telugu UI,Noto Sans Telugu UI Light",
  "Noto Sans Telugu UI,Noto Sans Telugu UI Medium",
  "Noto Sans Telugu UI,Noto Sans Telugu UI Thin",
  "Noto Sans Test",
  "Noto Sans Thaana,Noto Sans Thaana Black",
  "Noto Sans Thaana,Noto Sans Thaana Light",
  "Noto Sans Thaana,Noto Sans Thaana Medium",
  "Noto Sans Thaana,Noto Sans Thaana Thin",
  "Noto Sans Thai Looped",
  "Noto Sans Thai Looped,Noto Sans Thai Looped Black",
  "Noto Sans Thai Looped,Noto Sans Thai Looped Light",
  "Noto Sans Thai Looped,Noto Sans Thai Looped Medium",
  "Noto Sans Thai Looped,Noto Sans Thai Looped Thin",
  "Noto Sans Thai,Noto Sans Thai Blk",
  "Noto Sans Thai,Noto Sans Thai Light",
  "Noto Sans Thai,Noto Sans Thai Med",
  "Noto Sans Thai,Noto Sans Thai Thin",
  "Noto Sans Vithkuqi",
  "Noto Sans Vithkuqi,Noto Sans Vithkuqi Medium",
  "Noto Serif Armenian,Noto Serif Armenian Black",
  "Noto Serif Armenian,Noto Serif Armenian Light",
  "Noto Serif Armenian,Noto Serif Armenian Medium",
  "Noto Serif Armenian,Noto Serif Armenian Thin",
  "Noto Serif Bengali,Noto Serif Bengali Black",
  "Noto Serif Bengali,Noto Serif Bengali Light",
  "Noto Serif Bengali,Noto Serif Bengali Medium",
  "Noto Serif Bengali,Noto Serif Bengali Thin",
  "Noto Serif Devanagari,Noto Serif Devanagari Black",
  "Noto Serif Devanagari,Noto Serif Devanagari Light",
  "Noto Serif Devanagari,Noto Serif Devanagari Medium",
  "Noto Serif Devanagari,Noto Serif Devanagari Thin",
  "Noto Serif Display,Noto Serif Display Black",
  "Noto Serif Display,Noto Serif Display Light",
  "Noto Serif Display,Noto Serif Display Medium",
  "Noto Serif Display,Noto Serif Display Thin",
  "Noto Serif Dives Akuru",
  "Noto Serif Ethiopic,Noto Serif Ethiopic Black",
  "Noto Serif Ethiopic,Noto Serif Ethiopic Light",
  "Noto Serif Ethiopic,Noto Serif Ethiopic Medium",
  "Noto Serif Ethiopic,Noto Serif Ethiopic Thin",
  "Noto Serif Georgian,Noto Serif Georgian Bk",
  "Noto Serif Georgian,Noto Serif Georgian Lt",
  "Noto Serif Georgian,Noto Serif Georgian Md",
  "Noto Serif Georgian,Noto Serif Georgian Th",
  "Noto Serif Gujarati,Noto Serif Gujarati Black",
  "Noto Serif Gujarati,Noto Serif Gujarati Light",
  "Noto Serif Gujarati,Noto Serif Gujarati Medium",
  "Noto Serif Gujarati,Noto Serif Gujarati Thin",
  "Noto Serif Gurmukhi,Noto Serif Gurmukhi Black",
  "Noto Serif Gurmukhi,Noto Serif Gurmukhi Light",
  "Noto Serif Gurmukhi,Noto Serif Gurmukhi Medium",
  "Noto Serif Gurmukhi,Noto Serif Gurmukhi Thin",
  "Noto Serif Hebrew,Noto Serif Hebrew Black",
  "Noto Serif Hebrew,Noto Serif Hebrew Light",
  "Noto Serif Hebrew,Noto Serif Hebrew Medium",
  "Noto Serif Hebrew,Noto Serif Hebrew Thin",
  "Noto Serif Hentaigana",
  "Noto Serif Hentaigana,Noto Serif Hentaigana Black",
  "Noto Serif Hentaigana,Noto Serif Hentaigana Bold",
  "Noto Serif Hentaigana,Noto Serif Hentaigana Light",
  "Noto Serif Hentaigana,Noto Serif Hentaigana Medium",
  "Noto Serif Kannada,Noto Serif Kannada Black",
  "Noto Serif Kannada,Noto Serif Kannada Light",
  "Noto Serif Kannada,Noto Serif Kannada Medium",
  "Noto Serif Kannada,Noto Serif Kannada Thin",
  "Noto Serif Khitan Small Script",
  "Noto Serif Khmer,Noto Serif Khmer Black",
  "Noto Serif Khmer,Noto Serif Khmer Light",
  "Noto Serif Khmer,Noto Serif Khmer Medium",
  "Noto Serif Khmer,Noto Serif Khmer Thin",
  "Noto Serif Lao,Noto Serif Lao Black",
  "Noto Serif Lao,Noto Serif Lao Light",
  "Noto Serif Lao,Noto Serif Lao Medium",
  "Noto Serif Lao,Noto Serif Lao Thin",
  "Noto Serif Makasar",
  "Noto Serif Malayalam,Noto Serif Malayalam Black",
  "Noto Serif Malayalam,Noto Serif Malayalam Light",
  "Noto Serif Malayalam,Noto Serif Malayalam Medium",
  "Noto Serif Malayalam,Noto Serif Malayalam Thin",
  "Noto Serif Myanmar,Noto Serif Myanmar Black",
  "Noto Serif Myanmar,Noto Serif Myanmar Light",
  "Noto Serif Myanmar,Noto Serif Myanmar Medium",
  "Noto Serif Myanmar,Noto Serif Myanmar Thin",
  "Noto Serif,Noto Serif Black",
  "Noto Serif,Noto Serif Light",
  "Noto Serif,Noto Serif Medium",
  "Noto Serif,Noto Serif Thin",
  "Noto Serif NP Hmong",
  "Noto Serif NP Hmong,Noto Serif NP Hmong Medium",
  "Noto Serif Old Uyghur",
  "Noto Serif Oriya",
  "Noto Serif Oriya,Noto Serif Oriya Medium",
  "Noto Serif Ottoman Siyaq",
  "Noto Serif Sinhala,Noto Serif Sinhala Black",
  "Noto Serif Sinhala,Noto Serif Sinhala Light",
  "Noto Serif Sinhala,Noto Serif Sinhala Medium",
  "Noto Serif Sinhala,Noto Serif Sinhala Thin",
  "Noto Serif Tamil,Noto Serif Tamil Black",
  "Noto Serif Tamil,Noto Serif Tamil Light",
  "Noto Serif Tamil,Noto Serif Tamil Medium",
  "Noto Serif Tamil,Noto Serif Tamil Thin",
  "Noto Serif Telugu,Noto Serif Telugu Black",
  "Noto Serif Telugu,Noto Serif Telugu Light",
  "Noto Serif Telugu,Noto Serif Telugu Medium",
  "Noto Serif Telugu,Noto Serif Telugu Thin",
  "Noto Serif Test",
  "Noto Serif Thai,Noto Serif Thai Black",
  "Noto Serif Thai,Noto Serif Thai Light",
  "Noto Serif Thai,Noto Serif Thai Medium",
  "Noto Serif Thai,Noto Serif Thai Thin",
  "Noto Serif Tibetan,Noto Serif Tibetan Black",
  "Noto Serif Tibetan,Noto Serif Tibetan Light",
  "Noto Serif Tibetan,Noto Serif Tibetan Medium",
  "Noto Serif Tibetan,Noto Serif Tibetan Thin",
  "Noto Serif Todhri",
  "Noto Serif Toto",
  "Noto Serif Toto,Noto Serif Toto Medium",
  "Noto Serif Vithkuqi",
  "Noto Serif Vithkuqi,Noto Serif Vithkuqi Medium",
  "Noto Serif Yezidi,Noto Serif Yezidi Medium",
  "Noto Traditional Nushu,Noto Traditional Nushu Light",
  "Noto Znamenny Musical Notation",
  "Roboto Condensed",
  "Roboto Condensed,Roboto Condensed Light",
  "Roboto Condensed,Roboto Condensed Medium",
  "Roboto,Roboto Black",
  "Roboto,Roboto Light",
  "Roboto,Roboto Medium",
  "Roboto,Roboto Thin",
  "Schumacher Clean",
  "Schumacher Clean Wide",
  "Serto Batnan",
  "Serto Jerusalem",
  "Serto Jerusalem Outline",
  "Serto Kharput",
  "Serto Malankara",
  "Serto Mardin",
  "Serto Urhoy",
  "Share Tech Mono",
  "Sony Fixed",
  "Symbols Nerd Font",
  "Terminus",
  "Ubuntu Condensed",
  "UbuntuMono Nerd Font",
  "UbuntuMono Nerd Font Mono",
  "UbuntuMono Nerd Font Propo",
  "xos4 Terminus"
];
